### ISSUE TITLE
Text rendering accuracy in Safari when using iron-list inside iron-dropdown

### ISSUE THREAD

**Issue by platosha** [PolymerElements/iron-dropdown#40]
In Safari when scrolling a long iron-list placed inside an iron-dropdown, the items text is sometimes rendered 1 device pixel line outside the dropdown.

![image](https://cloud.githubusercontent.com/assets/247998/11629951/c8065374-9d03-11e5-9886-3e8b055dda5f.png)

## Expected outcome

The items text should not overflow outside the dropdown content element during vertical scroll.

## Actual outcome

The items text is sometimes rendered 1 device pixel line outside the dropdown content.

## Steps to reproduce

1. Create an iron-list with many items, assign background and dimentions in styles.
2. Wrap the iron-list with iron-dropdown
3. Assign a position target for iron-dropdown
4. Assign a non-integer pixel offset for the iron-dropdown position target. E. g.: `margin-top: 0.4px;`.
5. Toggle the dropdown and scroll the items list vertically

## Demo

http://jsfiddle.net/3mprhn5p/2/

The issue is visible in Safari 9.0.1 (OS X 10.10.5). Other Safari versions aren't tested.

More noticeable on non-retina screens.

Generally this seems to be a Safari rendering issue. Occurs when CSS transforms are applied on the element containing text, while the element’s parent is positioned on non-integer pixel coordinates.

The rendering issue could be reproduced without Polymer Elements and Web Components as well, see this demo: http://jsfiddle.net/fghtdh7r/6/

**Comment by valdrinkoshi** [comment]
@platosha I've tested it on safari 9.1.1 on a non-retina display and I can't repro with the latest `iron-dropdown` http://jsbin.com/yosuno/1/edit?html,output

no zoom:
![screen shot 2016-07-21 at 10 47 33 am](https://cloud.githubusercontent.com/assets/6173664/17032976/bb19e240-4f30-11e6-905f-f3f6c37d03bc.png)

zoomed:
![screen shot 2016-07-21 at 10 47 48 am](https://cloud.githubusercontent.com/assets/6173664/17032977/bb1f2c8c-4f30-11e6-9dde-bda7c6d74f75.png)

Most likely it got fixed in https://github.com/PolymerElements/iron-dropdown/pull/63 and then when we moved the `horizontal/verticalAlign` to `iron-fit-behavior`.

Closing for now, let me know if you still see the issue and I'll re-open this ;)

**Comment by platosha** [comment]
I still see it.

On your screenshots, it doesn’t look like you scrolled the dropdown content. You need to scroll it until the letters start to disappear at the top.
 
![image](https://cloud.githubusercontent.com/assets/247998/17049751/cdf9c228-4ff7-11e6-81f6-db92f41246d6.png)

**Comment by platosha** [comment]
@valdrinkoshi Hope you noticed my comment above.

**Comment by valdrinkoshi** [comment]
@platosha yeah sorry for the late reply. You're right, if we scroll a bit we can see that happening.
`iron-dropdown` will set its `top/left` with subpixel precision (done by `iron-fit-behavior` which uses `getBoundingClientRect`), and apparently Safari has issues with keeping the content within those bounds. e.g. I see `top: 59.828125px;`, in the dev console for `iron-dropdown`. I have to set that to `59px` for a proper rendering.
This issue should be moved to `iron-fit-behavior`

**Comment by valdrinkoshi** [comment]
This issue was moved to PolymerElements/iron-fit-behavior#63
